### PR TITLE
Leo/gh66 remove module by links - and scripts/

### PR DESCRIPTION
**Pull request by ranguard**
See https://github.com/perlorg/cpanorg/issues/66

### CODE REVIEW

**Review by rspier — CHANGES_REQUESTED** [review]
Discussion happening in #66

**Review by abh — APPROVED** [review]
Looks good to me.  @rspier?

After merging this we can remove the scripts/index.html file, I think.

**Comment by rspier** [comment]
Less is more.  Looks good.  Merging.

**Comment by abh** [comment]
@ranguard Have a look now?

**Comment by LeoLapworthKT** [comment]
> @ranguard Have a look now?

fab - thanks

**Comment by briandfoy** [comment]
As a note, this broke some Fedora tooling around packaging. I agree with the original poster that an advance announcement about this, perhaps at least on npc.perl.org, would have been appropriate.

**Comment by abh** [comment]
@briandfoy -- This change was just removing the links to the, uh, links (updating the HTML). We're still maintaining the actual symlinks on cpan.org. The report you read was about MetaCPAN which is a separate project.

I don't think we'd change that without having redirects in place at least for any existing URLs.

**Comment by ranguard** [comment]
I've posted on redit.. but for the records...

For now I have reverted MetaCPAN (NOT www.cpan.org) so we are NOT blocking `/modules/by-...` urls any more.

We are moving to an object store - for perforance, reliability, cost and maintaince reasons. Object stores do not support symlinks and converting the symlinks to files took the ~1 millions files we maintain to nearly 50 million! And many bots were downloading every link! We do not want to spend the donations we get on keeping copies of files that exist elsewhere and it also reduces our caching ability.

Please announce where ever packagers will see that they need to make the change and use the other tooling the CPAN provides to help with automation. We will leave it for 6 month before reinstating the block. So after 2025-06-01 we will block again.

If there are further issues please do contact us - https://metacpan.org/about/contact has all the options - the email address reaches the core team.

**Pull request merged**
