### PR TITLE
Update OpenSUSE release info

### PR DESCRIPTION
**Pull request by Tux**
Based on information on the openSUSE pages and the stack of CD's and DVD's I kept since version 5.1

I found info for SUSE versions 5.1, 5.2, 5.3, 6.1, 8.2, 9.1, 9.2, 9.3, 10.0, 10.1, 10.2, 10.3, 11.1, 11.2, 11.3, 11.4, 12.1, 12.2, 12.3, 13.1, 13.2, 42.1, 42.2, 42.3, 15.0 & TW
So I'm still missing 6.0, 6.[234]?, 7.x, 8.0, 8.1, 8.[345]?, 9.0 and 11.0
My 11.0 CD just had the boot, no packages :(

### CODE REVIEW

**Comment by abh** [comment]
Nice, thanks. :-)

**Comment by Tux** [comment]
Do you want updates for all other OS's too? Ill base it on https://github.com/Tux/System-Info/blob/master/sandbox/dist-perl.csv

**Comment by ranguard** [comment]
@Tux sure - would be great

**Comment by abh** [comment]
We need to change the UI a bit though, I think. The page is getting goofy long with historical information.

**Comment by Tux** [comment]
As I see that https://www.cpan.org/ports/binaries.html still shows the outdated list, should I just wait for updates?

**Pull request merged**
