### PR TITLE
FAQ - Remove mention of obsolete module list, mention Task::Kensho instead

### PR DESCRIPTION
**Pull request by Grinnz**
The modulelist is no longer used. Task::Kensho seems worth mentioning in this context.

### CODE REVIEW

**Comment by abh** [comment]
Not sending people to the module list makes sense.

Is Task::Kensho generally accepted as being "the right choices" (versus just the opinion of a few people?).

**Comment by ranguard** [comment]
Approved as over the years I've seen the Task::Kensho team try to make sure they are promoting what is widely accepted as 'the right choice' vs personal preferences

**Comment by Grinnz** [comment]
I don't think anything could be considered more than the opinion of a few people...such is CPAN. But Task::Kensho has been seeking community comments. Unfortunately more general metrics like "number of ++ on metacpan" are far from a good way to recommend modules on their own.

**Comment by Grinnz** [comment]
This seems to have gotten closed due to the deletion of the branch?

**Pull request closed without merging**
